HAN-81-89-90-91-96
Koreatech-Thunder/Thunder-Server pull request #12
Opened 2023-03-08 02:54 UTC by hansongyi2020

## 관련 이슈 번호 🔎

- HAN-81-89-90-91-96

<br>

## 주요 변경 사항 🔑

- controller, service user thunder 파일 추가
- routers index.ts 추가

<br>

## 하고싶은 말 📢

-

<br>

## 관련 스크린샷 (선택) 📷

-

<br>

## 참고자료 📚

-

<br>

2023-03-08 04:53 UTC, KWY0218 requested changes
커멘트 확인해주세요~!

2023-03-08 04:53 UTC, KWY0218 commented on src/services/user/UserService.ts
> +};
user update api인 것 같은데 유저의 정보를 가져오기만 하고 user의 정보를 update는 하지 않아 보입니다...!

2023-03-08 04:54 UTC, KWY0218 commented
또한 나머지 작업도 이 브랜치에서 작업하고 푸시해주면 좋을 것 같습니다~!

2023-03-08 13:10 UTC, Vrickk requested changes

2023-03-08 13:10 UTC, Vrickk commented on src/routes/UserRouter.ts
> -router.delete('/:userId', UserController.deleteUser);
delete 라우터가 아예 삭제됐네요. Axios때문에 삭제된건가요?

2023-03-08 13:10 UTC, Vrickk commented on src/services/user/UserService.ts
> +};
@KWY0218

이거는 제가 #11 에서 한겁니다. GET 맞습니다.


[HAN-79](https://github.com/Koreatech-Thunder/Thunder-Server/pull/11)

2023-03-08 17:24 UTC, KWY0218 requested changes
문서화가 체크된 상태면 그 때 다시 에러처리 리뷰하겠습니다..!
전체적으로 아주 좋은 것 같습니다..!
특히 변수 타입, 리턴 타입 을 전부 붙여준 것이 너무 좋은 것 같습니다!!
작업하시느라 수고하셨습니다!!
코멘트 확인해주세요~~!

2023-03-08 17:24 UTC, KWY0218 commented on src/controllers/user/UserController.ts
> +  }
service에서 404 error를 던질 수 있는데 controller에서  catch 로직이 없는 것 같습니다.

2023-03-08 17:24 UTC, KWY0218 commented on src/services/user/ThunderService.ts
> +
최신순으로 보일려면 0번째 인덱스에 제일 최근 번개가 와야해서 `desc` 내림차순이 맞지 않나란 생각이 듭니다..!
@Vrickk @hansongyi2020  두 분 생각은 어떤가유???

2023-03-08 17:24 UTC, KWY0218 commented on src/services/user/ThunderService.ts
> +      thunderlist.map(async (all: any) => {
```suggestion
      thunderlist.map(async (thunder: any) => {
```
thunderList에서 thunder들을 하나하나 보는 것이므로, 
네이밍이 `all` 보다 `thunder`로 하는 것이 가독성이 더 좋을 것 같습니다..!!

2023-03-08 17:24 UTC, KWY0218 commented on src/services/user/ThunderServiceUtils.ts
> +};
함수 좋습니다!!!!
살짝 아쉬운 점은 1, 2, 0 를 리턴할 때 메직넘버를 리턴한다고 말합니다.
무슨 말이냐면 어떤 값인지 해석이 잘 안된다는 뜻입니다.
`const HOST = 1` 과 같은 상수를 이용한다면 가독성이 더 좋아질 것 입니다!!

2023-03-08 17:24 UTC, KWY0218 commented on src/services/user/ThunderService.ts
> +            thunderState: 'MEMBER',
여기서도 매직넘버를 사용하므로 상수말고, enum class를 활용한 방법도 좋을 것 같다고 생각합니다.

2023-03-08 17:24 UTC, KWY0218 commented on src/services/user/ThunderService.ts
> +): Promise<ThunderResponseDto[] | []> => {
get thuder list api 리뷰 내용과 동일합니다..!

2023-03-09 02:06 UTC, hansongyi2020 commented on src/services/user/ThunderService.ts
> +
네! 내림차순 맞는 것 같습니다! 수정하겠습니다!

2023-03-09 02:07 UTC, hansongyi2020 commented on src/services/user/ThunderService.ts
> +      thunderlist.map(async (all: any) => {
네! 변수명 고려하겠습니다

2023-03-09 02:07 UTC, HANSONGYI1218 commented on src/services/user/ThunderServiceUtils.ts
> +};
네! 알겠습니다!

2023-03-09 02:07 UTC, hansongyi2020 commented on src/services/user/ThunderService.ts
> +            thunderState: 'MEMBER',
알겠습니다!!

2023-03-09 02:08 UTC, hansongyi2020 commented on src/routes/UserRouter.ts
> -router.delete('/:userId', UserController.deleteUser);
삭제되었네요..! 나중에 merge할 때 수정하겠습니다!

2023-03-09 02:09 UTC, hansongyi2020 commented on src/controllers/user/UserController.ts
> +  }
네! controller catch 로직 작업 구현해야 합니다!

2023-03-09 10:19 UTC, Vrickk approved these changes
수고하셨습니다!

2023-03-09 10:19 UTC, Vrickk commented on src/services/user/ThunderService.ts
> +      createdAt: 'asc',
여기도 최신순으로 보이려면 desc로 바꿔야 할 것 같습니다!

2023-03-09 10:19 UTC, Vrickk commented on src/services/user/UserService.ts
> +const deleteUser = async (userId: string) => {
[HAN-112](https://koreatech-hanbun.atlassian.net/browse/HAN-112?atlOrigin=eyJpIjoiMDcwNzA3MjZlMjZiNGZjNDg4NDJkNzlkYzc1ZGY5ZTMiLCJwIjoiaiJ9)에서 axios 부분을 삭제했습니다. Conflict Resolve할 때 axios 관련 부분만 삭제하고 주석 풀어주시면 될 것 같습니다!

2023-03-09 10:19 UTC, Vrickk commented on src/services/user/UserService.ts
> +    const data: UserInfoDto | null = await User.findById(userId);
여기도 HAN-112에서 수정한 내용으로 conflict resolve 해주시면 될것같습니다..!

2023-03-13 02:30 UTC, hansongyi2020 commented on src/services/user/UserService.ts
> +const deleteUser = async (userId: string) => {
알겠습니다!

2023-03-13 02:30 UTC, hansongyi2020 commented on src/services/user/UserService.ts
> +    const data: UserInfoDto | null = await User.findById(userId);
네!

2023-03-13 08:16 UTC, Vrickk approved these changes

2023-03-13 08:22 UTC, KWY0218 requested changes
커멘트 확인바랍니다~

또, 이번에 develop 브랜치에 미들웨어가 추가됐습니다.
미들웨어 pr에서 사용법을 익히거나 승벽이한테 질문해서 이번 피알에서도 적용하면 좋을 것 같습니다.

또한 상수화에 대해 알아보는 것도 좋을 것 같습니다

2023-03-13 08:22 UTC, KWY0218 commented on src/controllers/user/UserController.ts
> +    } else if ('유효하지 않은 id입니다.') {
`error.msg ==` 해야하지 않나요..?
이게...빌드가 되나요...? 신기하네..

2023-03-13 08:22 UTC, KWY0218 commented on src/services/thunder/ThunderService.ts
> +      thunderlist.map(async (hashtag: any) => {
hashtag란 이름은 어색한 것 같습니다.
여기도 thunder가 적절한 것 같습니다.

2023-03-13 08:22 UTC, KWY0218 commented on src/services/thunder/ThunderServiceUtils.ts
> +};
이거 생각해보니까 0번째 index가 userId가 아니면 무조건 non_member가 리턴 될 것 같습니다.

로직 수정 바랍니다.

2023-03-13 08:24 UTC, KWY0218 commented on src/services/thunder/ThunderServiceUtils.ts
> +const findMemberById = async (userId: string, list: string[]) => {
리턴 타입도 넣으면 좋을거 같아요~

2023-03-13 09:22 UTC, hansongyi2020 commented on src/controllers/user/UserController.ts
> +    } else if ('유효하지 않은 id입니다.') {
아! 빌드 되긴 했는데! 수정하겠습니다...!

2023-03-14 07:02 UTC, KWY0218 reviewed
코멘트 확인해주세요~!

2023-03-14 07:02 UTC, KWY0218 commented on src/services/thunder/ThunderServiceUtils.ts
> +  return 'NON_MEMBER';
반복문 밖에서 userId == [0] 이라면 `host` 리턴
반복문 안에서는 1 부터 list size 까지 반복을 하고 그 안에 userId가 있음 `member` 를 리턴
반복문이 끝날 때 return `NON_MEMBER` 리턴

이런식으로 로직짜면 좋을 것 같습니다.

2023-03-14 07:21 UTC, KWY0218 commented on src/services/user/UserService.ts
> +};
음... 뭔가 update 말고 유저를 create 하는 로직 같은 느낌이 드는데...
@Vrickk  update 로직이 맞을까요..?

2023-03-14 07:23 UTC, Vrickk commented on src/services/user/UserService.ts
> +};
new User면은 새로운 User 객체를 생성하는거니까 update보단 create에 가까운게 맞는것 같습니다.

2023-03-14 07:36 UTC, hansongyi2020 commented on src/services/user/UserService.ts
> +};
이 부분 다시 구현해 보겠습니다..!

2023-03-14 08:05 UTC, Vrickk commented on src/services/user/UserService.ts
> +  userUpdateDto: UserUpdateDto,
UserUpdateDto 파일 체인지는 확인되지 않는데 develop 브랜치의 userUpdateDto.ts 기준인가요?

2023-03-14 08:11 UTC, KWY0218 reviewed
미들웨어도 적용하면 좋을 것 같습니다..!

2023-03-14 08:11 UTC, KWY0218 commented on src/controllers/user/UserController.ts
> +      res.status(statusCode.CONFLICT).send(statusCode.CONFLICT);
UserService 에서 해당 에러는 throw 하지 않아서 삭제해도 되는 로직 같습니다

2023-03-14 09:55 UTC, Vrickk commented
mongoose-auto-increment 모듈은 더 이상 사용되지 않습니다. 따라서 package.json을 비롯한 설정 파일에서 해당 모듈 관련 내용만 지워주시고 머지하면 될 것 같습니다!

2023-03-14 15:17 UTC, Vrickk reviewed
제가 구현한 Router는 HAN-113 #16 에서 미들웨어 적용했습니다.

2023-03-14 16:58 UTC, KWY0218 requested changes

2023-03-14 16:58 UTC, KWY0218 commented on src/controllers/user/UserController.ts
> +  const {userId} = req.params;
미들웨어를 적용하면 paprams가 아닌 body에서 userId를 가져오는 것으로 알고 있습니다..!
나머지들도 반영해주세요..!

2023-03-15 10:45 UTC, Vrickk requested changes
🚀코멘트 확인해주세요!

2023-03-15 10:45 UTC, Vrickk commented on src/controllers/thunder/ThunderController.ts
> +  const {userId} = req.params;
미들웨어 경유하는 경유에는 params 대신 body값을 받도록 수정해주시면 될 것 같습니다.

2023-03-15 10:45 UTC, Vrickk commented on src/services/thunder/ThunderService.ts
> +  await UserServiceUtils.findUserById(userId);
이 코드는 해당 메서드 내에서 아무 기능도 하지 않는 것으로 보입니다. 어떤 역할을 하나요?

2023-03-15 10:45 UTC, Vrickk commented on src/services/thunder/ThunderService.ts
> +    await UserServiceUtils.findUserById(userId);
> 이 코드는 해당 메서드 내에서 아무 기능도 하지 않는 것으로 보입니다. 어떤 역할을 하나요?

위와 동일한 이유로 코멘트 달았습니다.

2023-03-17 15:43 UTC, hansongyi2020 commented on src/controllers/user/UserController.ts
> +  const {userId} = req.params;
확인 했습니다!

2023-03-17 15:45 UTC, hansongyi2020 commented on src/services/thunder/ThunderService.ts
> +  await UserServiceUtils.findUserById(userId);
모든 API마다 userId가 db에 존재하는지 확인한 후 다음 순서를 진행하는 식으로 구현 했는데 이 부분은 auth 부분에서 구현이 됐다고 해 지웠습니다..!

2023-03-18 09:18 UTC, KWY0218 approved these changes
구웃~ 👍

2023-03-18 09:20 UTC, Vrickk commented
LGTM👍

2023-03-18 09:21 UTC, Vrickk approved these changes
LGTM 👍

2023-03-18 10:19 UTC, merged