[feat] FCM 알림 발송 기능 작성.
Koreatech-Thunder/Thunder-Server pull request #15
Opened 2023-03-12 09:17 UTC by Vrickk

## 관련 이슈 번호 🔎

[HAN-101](https://koreatech-hanbun.atlassian.net/browse/HAN-101?atlOrigin=eyJpIjoiNDgwN2JlNjU2MWQ5NDBiMDhiMTg5Yjk1MWJmMmY1MTkiLCJwIjoiaiJ9)

<br>

## 주요 변경 사항 🔑

- 1. userId를 param으로 받고 그 userId를 가진 유저에게 FCM 알림을 발송하는 pushAlarmToUser 기능을 작성했습니다.
- 2. db.ts에서 firebase를 initialize하고, 메시지 발송 기능을 테스트하는 부분을 작성했습니다.

<br>

## 하고싶은 말 📢

-

<br>

## 관련 스크린샷 (선택) 📷

-

<br>

## 참고자료 📚

-

<br>

2023-03-12 09:45 UTC, KWY0218 requested changes
빠른 작업 감사합니당~ 코멘트 확인해주세요~ 😄

2023-03-12 09:45 UTC, KWY0218 commented on src/controllers/UserController.ts
> +}
푸시 알림을 API로 만들어서 클라이언트가 사용하는 것이 아닙니다..!
푸시알림은
1. 번개를 생성하고 해당 해시태그를 저장한 유저들에게 알림을 보낼 때
2. 오프라인 유저에게 푸시 알림을 보낼 때
위 두 상황에서 푸시 알림을 보내고 있습니다.
그래서 위 상황일 때 편하게 사용하기 위해 메서드를 만들어달라고 요청한 것입니다..!

따라서 API로 만드는 것이 아닌 메서드로 만드는 것으로 충분합니다..!!

2023-03-12 09:45 UTC, KWY0218 commented on src/interfaces/user/UserAlarmBaseDto.ts
> +}
그렇기 때문에 굳이 userId 를 보내줄 때 객체로 만들지 말고 userId: string으로 매개변수를 받아도 될 것 같습니다.

2023-03-12 10:46 UTC, Vrickk commented on src/controllers/UserController.ts
> +}
모듈 파일로 독립시키는 것으로 수정하였습니다.

2023-03-12 11:01 UTC, KWY0218 commented on src/interfaces/user/UserCreateDto.ts
> +    refreshToken?: String;
혹시.... 이걸 가지고 있어야 할 이유가 있을까요...? 저번 리뷰에 말했던 것 같아서요..!!

2023-03-12 11:15 UTC, Vrickk commented on src/interfaces/user/UserCreateDto.ts
> +    refreshToken?: String;
삭제했습니다.

2023-03-12 14:14 UTC, KWY0218 commented on src/interfaces/user/UserCreateDto.ts
> +    refreshToken?: String;
앗 accesstoken이랑 refreshtoken 만 말한거였는데....

2023-03-12 14:23 UTC, Vrickk commented on src/interfaces/user/UserCreateDto.ts
> +    refreshToken?: String;
저번에 createUser를 삭제해서 createDto는 굳이 필요하지 않을것같아서 삭제했는데
지금 보니까 ResponseDto에서 extend를 받고있네요
그래서 다시 복구했습니다..!

2023-03-12 16:43 UTC, KWY0218 approved these changes
좋은 것 같아요~!

2023-03-13 02:15 UTC, hansongyi2020 approved these changes

2023-03-13 08:13 UTC, merged