HAN-92 [feat] put thunder
Koreatech-Thunder/Thunder-Server pull request #17
Opened 2023-03-14 16:58 UTC by hansongyi2020

## 관련 이슈 번호 🔎

- HAN-92

<br>

## 주요 변경 사항 🔑

- create put thunder api

<br>

## 하고싶은 말 📢

- ThunderUpdateDto  봐 주세요!!

<br>

## 관련 스크린샷 (선택) 📷

-

<br>

## 참고자료 📚

-

<br>

2023-03-14 17:12 UTC, KWY0218 requested changes
미들웨어 PR

2023-03-14 17:12 UTC, KWY0218 commented on src/controllers/thunder/ThunderController.ts
> +  const userId = req.params.userId;
미들웨어 피알 참고해서 수정하면 될 것 같습니다..!

2023-03-15 12:10 UTC, Vrickk requested changes
수고하셨습니다 😀

2023-03-15 12:10 UTC, Vrickk commented on src/routes/ThunderRouter.ts
> +router.get('/:userId/:thunderId', auth.auth, ThunderController.findThunder);
미들웨어를 거친다면 :userId param 입력 부분은 굳이 필요하지 않을 것 같습니다.

2023-03-15 12:10 UTC, Vrickk commented on src/routes/UserRouter.ts
> 미들웨어를 거친다면 :userId param 입력 부분은 굳이 필요하지 않을 것 같습니다.

여기도 미들웨어 적용 후 수정해주시면 될 것 같습니다.

2023-03-15 12:10 UTC, Vrickk commented on src/services/thunder/ThunderService.ts
> +    await UserServiceUtils.findUserById(userId);
findUserById가 실행만 되고 해당 메서드로 불러온 유저 정보는 어디에도 저장되지 않는 것으로 보입니다. 해당 구절이 이 메서드에서 어떤 역할을 하는지 알 수 있을까요?

2023-03-17 15:51 UTC, hansongyi2020 commented on src/controllers/thunder/ThunderController.ts
> +  const userId = req.params.userId;
네!

2023-03-17 15:52 UTC, hansongyi2020 commented on src/services/thunder/ThunderService.ts
> +    await UserServiceUtils.findUserById(userId);
유저가 db에 있는지 확인하는 용도 입니다. 이 부분은 auth 에서 구현했기에 모든 API 에서 지웠습니다!

2023-03-18 09:25 UTC, KWY0218 reviewed
코멘트 외에  좋습니다~

2023-03-18 09:25 UTC, KWY0218 commented on src/controllers/thunder/ThunderController.ts
> +  const thunderId: string = req.body['thunderId'];
라우터로 `:thunderId` 로 들어온 값도 body 안에 들어있나요...? (진짜 모름)
@Vrickk @hansongyi2020

2023-03-18 09:30 UTC, Vrickk commented on src/controllers/thunder/ThunderController.ts
> +  const thunderId: string = req.body['thunderId'];
`:thunderId`는 params 아닌가요?

2023-03-18 09:34 UTC, KWY0218 commented on src/controllers/thunder/ThunderController.ts
> +  const thunderId: string = req.body['thunderId'];
@hansongyi2020  수정 바랍니다~

2023-03-18 10:02 UTC, KWY0218 approved these changes
👍

2023-03-18 10:07 UTC, Vrickk approved these changes

2023-03-20 02:26 UTC, merged