HAN-94 [feat] get thunder detail
Koreatech-Thunder/Thunder-Server pull request #18
Opened 2023-03-14 16:59 UTC by hansongyi2020

## 관련 이슈 번호 🔎

- HAN-94

<br>

## 주요 변경 사항 🔑

- create get thunder detail

<br>

## 하고싶은 말 📢

- ThunderResponseDto 로 했는데 맞는지 확인해 주세요!!

<br>

## 관련 스크린샷 (선택) 📷

-

<br>

## 참고자료 📚

-

<br>

2023-03-14 17:10 UTC, KWY0218 requested changes

2023-03-14 17:10 UTC, KWY0218 commented on src/services/thunder/ThunderService.ts
> +    await UserServiceUtils.findUserById(userId);
송이 코드에서 모든 메서드에 findUserById로 userId가 유효한지 확인하고 있는데,
미들웨어에서 하고 넘기면 반복되는 로직을 없앨 수 있을 것 같습니다..!
@Vrickk  어떻게 생각하시나용?

2023-03-14 17:10 UTC, KWY0218 commented on src/services/thunder/ThunderService.ts
> +): Promise<ThunderResponseDto> => {
thunder detail API는 번개 수정하기를 위한 API로 알고 있습니다.
그래서 지금도 사용은 가능한데, 초반에 말했던 필요한 정보만 주는 것을 목표로 한다면 불필요한 속성들도 보입니다.  

그래서 필요한 정보를 준다면 수정하기 뷰를 참고하면서 새 DTO를 만들어야 할 것 같습니다.

2023-03-14 17:10 UTC, KWY0218 commented on src/controllers/thunder/ThunderController.ts
> +  const userId = req.params.userId;
미들웨어 PR 리뷰 단 거 참고해서 변경해주세요..!

2023-03-15 02:56 UTC, Vrickk commented on src/services/thunder/ThunderService.ts
> +    await UserServiceUtils.findUserById(userId);
미들웨어에서 유저 id가 유효한지 확인하고 만약 없다면 에러코드를 전송하는 단락이 존재합니다
`
const user = await User.findById(userId.id);
        if (!user) { //userId는 있지만 해당 id를 가진 유저 정보가 없으면 에러.
            return res.status(statusCode.NOT_FOUND).send(statusCode.NOT_FOUND);
        }
`

2023-03-15 03:08 UTC, Vrickk requested changes

2023-03-15 03:08 UTC, Vrickk commented on src/routes/ThunderRouter.ts
> +router.get('/:userId', auth.auth, ThunderController.findThunderAll);
이렇게 param으로 값을 입력받는 라우터들을 body로 받게끔 하면 오류가 해결될 것 같습니다..!

2023-03-15 03:30 UTC, KWY0218 commented on src/services/thunder/ThunderService.ts
> +    await UserServiceUtils.findUserById(userId);
그러면 저 로직은 service 단에 없어도 되겠네요~

2023-03-15 12:57 UTC, Vrickk approved these changes

2023-03-15 12:59 UTC, Vrickk requested changes
체인지를 잘못 했습니다

2023-03-18 09:36 UTC, KWY0218 requested changes
코멘트 확인해주세요~

2023-03-18 09:36 UTC, KWY0218 commented on src/controllers/thunder/ThunderController.ts
> +  const thunderId: string = req.body['thunderId'];
요기도 params ~

2023-03-18 09:36 UTC, KWY0218 commented on src/services/thunder/ThunderService.ts
> +    }
thunder state 를 구하는 해당 로직은 필요없어 보입니다..!

2023-03-18 10:01 UTC, KWY0218 approved these changes
구웃~ conflict 해결하고 아래 피알부터 머지해줘요~

2023-03-18 10:07 UTC, Vrickk approved these changes

2023-03-18 10:27 UTC, KWY0218 commented on src/services/thunder/ThunderService.ts
> +    }
@hansongyi2020 요거!!

2023-03-18 10:42 UTC, Vrickk approved these changes

2023-03-18 14:56 UTC, KWY0218 commented on src/routes/ThunderRouter.ts
> +router.get('/:thunderId', ThunderController.findThunder);
미들웨어를 적용안하는 이유가 있을까요...?

2023-03-20 02:07 UTC, hansongyi2020 commented on src/routes/ThunderRouter.ts
> +router.get('/:thunderId', ThunderController.findThunder);
아! 제가 잘못 이해해서 지운 것 같습니다..! 정정했습니다

2023-03-20 02:16 UTC, merged