HAN-95 [feat] put join thunder
Koreatech-Thunder/Thunder-Server pull request #19
Opened 2023-03-14 18:37 UTC by hansongyi2020

## 관련 이슈 번호 🔎

- HAN-95

<br>

## 주요 변경 사항 🔑

- put join thunder

<br>

## 하고싶은 말 📢

- members list[0] HOST 고정 잘 되면서  userId 추가됩니다!

<br>

## 관련 스크린샷 (선택) 📷

-

<br>

## 참고자료 📚

-

<br>

2023-03-15 00:15 UTC, KWY0218 requested changes
코멘트 확인해주세요~

2023-03-15 00:15 UTC, KWY0218 commented on src/services/thunder/ThunderService.ts
> +    }
`>=` 해야 4/4 상황일 때 추가가 안될 것 같습니다

2023-03-15 00:15 UTC, KWY0218 commented on src/services/thunder/ThunderService.ts
> +      await Thunder.findByIdAndUpdate(thunderId, {$push: {members: userId}});
👍

2023-03-15 00:15 UTC, KWY0218 commented on src/controllers/thunder/ThunderController.ts
> +  const userId = req.params.userId;
미들웨어 참고해주세요~

2023-03-15 00:15 UTC, KWY0218 commented on src/controllers/thunder/ThunderController.ts
> + * @access Public
userId는 Path 가 아닌 access token 내에 있습니다

2023-03-15 00:19 UTC, KWY0218 requested changes

2023-03-15 00:19 UTC, KWY0218 commented on src/routes/ThunderRouter.ts
> +router.put('/join/:userId/:thunderId', ThunderController.joinThunder);
1. 미들웨어 적용해주세요
2. userId는 access token 내에 있으며 미들웨어에서 추출할 것입니다. 확인해주세요

2023-03-15 12:39 UTC, Vrickk requested changes
👍👍

2023-03-15 12:39 UTC, Vrickk commented on src/routes/UserRouter.ts
> +router.put('/:userId', auth.auth, UserController.updateUser);
미들웨어가 연결됐다면 더이상 params로 userId를 받을 필요가 없을 것 같습니다..!

2023-03-18 09:24 UTC, Vrickk approved these changes

2023-03-18 09:40 UTC, KWY0218 requested changes
params 수정만 하면 될 것 같습니다~

2023-03-18 09:40 UTC, KWY0218 commented on src/controllers/thunder/ThunderController.ts
> +  const thunderId: string = req.body['thunderId'];
params~

2023-03-18 10:04 UTC, KWY0218 approved these changes
👍

2023-03-18 10:08 UTC, Vrickk approved these changes

2023-03-20 02:27 UTC, merged