HAN-93 [feat] put out thunder
Koreatech-Thunder/Thunder-Server pull request #20
Opened 2023-03-14 19:25 UTC by hansongyi2020

## 관련 이슈 번호 🔎

- HAN-93

<br>

## 주요 변경 사항 🔑

- put out thunder

<br>

## 하고싶은 말 📢

-

<br>

## 관련 스크린샷 (선택) 📷

-

<br>

## 참고자료 📚

-

<br>

2023-03-15 00:18 UTC, KWY0218 requested changes

2023-03-15 00:18 UTC, KWY0218 commented on src/controllers/thunder/ThunderController.ts
> +  const userId = req.params.userId;
미들웨어 적용해주세요~

2023-03-15 00:18 UTC, KWY0218 commented on src/routes/ThunderRouter.ts
> +router.put('/out/:userId/:thunderId', ThunderController.outThunder);
미들웨어 적용해주세요~

2023-03-15 12:27 UTC, Vrickk approved these changes
미들웨어 관련내용만 수정하면 될것같습니다~~ 👍

2023-03-17 15:06 UTC, hansongyi2020 commented on src/controllers/thunder/ThunderController.ts
> +  const userId = req.params.userId;
적용했습니다!

2023-03-17 15:06 UTC, hansongyi2020 commented on src/routes/ThunderRouter.ts
> +router.put('/out/:userId/:thunderId', ThunderController.outThunder);
적용했습니다!

2023-03-17 15:10 UTC, hansongyi2020 commented
![image](https://user-images.githubusercontent.com/74229148/225944354-95b15195-6dc6-4e67-a4c1-01a977b8cca7.png)
@Vrickk 이런식으로 message 모듈 불러와서 명시하면 좋을 것 같습니다~!

2023-03-18 09:42 UTC, KWY0218 requested changes
여기두 params 만 적용하면 될 것 같습니다~ 👍

2023-03-18 09:42 UTC, KWY0218 commented on src/controllers/thunder/ThunderController.ts
> +  const thunderId: string = req.body['thunderId'];
params ~

2023-03-18 10:05 UTC, KWY0218 approved these changes
👍

2023-03-18 10:08 UTC, Vrickk approved these changes

2023-03-20 02:27 UTC, merged