[feat] 채팅 관련 DTO 및 메서드 추가.
Koreatech-Thunder/Thunder-Server pull request #22
Opened 2023-03-18 12:40 UTC by Vrickk

## 관련 이슈 번호 🔎

- [HAN-114](https://koreatech-hanbun.atlassian.net/browse/HAN-114?atlOrigin=eyJpIjoiMjAwOGE4MjNhMjg5NGU4ZDhmZDEzM2E0ZjRhODFmZDEiLCJwIjoiaiJ9)

<br>

## 주요 변경 사항 🔑

- 1. 채팅 관련 DTO 파일들 우선 추가.
- 2. 기존 스키마 및 Info 파일 채팅 기능에 맞게 수정.

<br>

## 하고싶은 말 📢

-

<br>

## 관련 스크린샷 (선택) 📷

-

<br>

## 참고자료 📚

-

<br>

2023-03-19 07:14 UTC, KWY0218 reviewed
![image](https://user-images.githubusercontent.com/82709044/226159959-cf189c77-b34e-4406-ac08-8d9ca5e0ac58.png)

`PersonalChatRoomInfo`  , `ThunderRecord`
model 도 추가해야 될 것 같습니다 해당 이미지는 졸작 collection 명세서 페이지에 올려놓을게요~!

2023-03-19 12:55 UTC, KWY0218 reviewed
ref을 넣지 않아도 될지라도 
ref을 넣어준다면 해당 ObjectId가 무엇을 참고하는지 알 수 있어서 좋을 것 같습니다

2023-03-19 12:55 UTC, KWY0218 commented on src/models/Thunder.ts
> +      type: mongoose.Schema.Types.ObjectId, //PersonalChatRoomInfo.id
ref을 `PersonalChatRoom 으로 변경해야 될 것 같습니다

2023-03-19 12:55 UTC, KWY0218 commented on src/models/PersonalChatRoom.ts
> +  },
`ref: User`

2023-03-19 12:55 UTC, KWY0218 commented on src/models/ThunderRecord.ts
> +  },
ref : Thunder

2023-03-19 12:55 UTC, KWY0218 commented on src/models/User.ts
> +  },
ref : ThunderRecord

2023-03-19 13:58 UTC, Vrickk commented on src/models/Thunder.ts
> +      type: mongoose.Schema.Types.ObjectId, //PersonalChatRoomInfo.id
Ref 전부 추가했습니다.

2023-03-19 15:08 UTC, KWY0218 requested changes
작업하시느라 수고하셨습니다..!
로직 대부분이 좋아서 조금만 수정하면 될 것 같습니다.
한가지 아쉬운 점은 반환 타입을 명시해주면 가독성이 더 좋아질 것 같습니다..!

2023-03-19 15:08 UTC, KWY0218 commented on src/models/Thunder.ts
> +      type: String,
string이 아닌 ref : chat 아닌가요?!

2023-03-19 15:08 UTC, KWY0218 commented on src/modules/chattingHandler.ts
> +    });
반환 타입 적어주면 가독성이 좋아질 것 같습니당

2023-03-19 15:08 UTC, KWY0218 commented on src/modules/chattingHandler.ts
> +    const user = await User.findById(userId);
반환 타입을 적으면 가독성 좋아질 것 같습니다

2023-03-19 15:08 UTC, KWY0218 commented on src/modules/chattingHandler.ts
> +const updateThunder = async (thunderId: string, members: string[]) => {
이제와서 든 생각이지만 `updateThunderMembers` 메서드 명이 더욱 직관적일 것 같네요 ㅎㅎ..

2023-03-19 15:08 UTC, KWY0218 commented on src/modules/chattingHandler.ts
> +};
여기서 chat을 save 한 후 id 값을 추출한 다음 push를 해야합니다!!

2023-03-19 15:08 UTC, KWY0218 commented on src/modules/chattingHandler.ts
> +};
아 현재 User 스키마에 
![image](https://user-images.githubusercontent.com/82709044/226185247-81ff9f00-4683-4b0d-b2cc-77d797d22024.png)
이부분이 속성 추가가 안된 것 같습니다.
isAlarm 함수는 여기서 3번째 `채팅알림받기` on / off 여부를 반환하는 함수입니다.
User Entity 내에 `boolean[] ` 하나를 만들면 될 것 같습니다.,,!
0번째 index : `해시태그 별 알림`
1번째 index : `평가 알림 받기`
2번째 index : `채팅 알림 받기`

2023-03-19 15:31 UTC, Vrickk commented on src/modules/chattingHandler.ts
> +};
반대 아닌가요? 매개변수로 새로 들어온 chat 값을 기존 chats 리스트에 추가 후 DB에 저장하는게 맞다면 push 후에 save해야하지 않을까요?

2023-03-19 15:32 UTC, Vrickk commented on src/modules/chattingHandler.ts
> +};
추가했습니다.

2023-03-19 15:32 UTC, Vrickk commented on src/modules/chattingHandler.ts
> +const updateThunder = async (thunderId: string, members: string[]) => {
변경했습니다

2023-03-19 15:56 UTC, KWY0218 commented on src/modules/chattingHandler.ts
> +};
그치만 save 하지 않으면 chat id 가  안생기지 않나요??
저는 id는 db에 추가된 후에 생성되는 것으로 알고 있습니다...!
아니면 말해주세요~~!

2023-03-19 15:57 UTC, KWY0218 commented on src/models/User.ts
> +      default: [false, false, false],
힝... true true true 하좌... 😭

2023-03-19 16:12 UTC, Vrickk commented on src/modules/chattingHandler.ts
> +};
chat을 먼저 세이브하려면 ChatDto가 아니라 스키마인 Chat을 사용해야 할겁니다...

2023-03-20 02:26 UTC, KWY0218 reviewed
함수, 변수 반환타입 써주면 감사티비..

2023-03-20 02:26 UTC, KWY0218 commented on src/modules/chattingHandler.ts
> +    return result;
getThunders 라서 Thunder[] 타입이 와야할 것 같은데
이렇게 하면 단일 Thunder만 오는 것이 아닌가요??

2023-03-20 02:26 UTC, KWY0218 commented on src/services/ChatService.ts
> +};
미완성 부분인 것 같습니다..!

2023-03-20 02:26 UTC, KWY0218 commented on src/modules/chattingHandler.ts
> +};
그럼 소켓 로직에서 save 하겠슴당~

2023-03-20 03:10 UTC, Vrickk commented on src/services/ChatService.ts
> +};
맞습니다...

2023-03-20 03:22 UTC, hansongyi2020 approved these changes

2023-03-20 03:24 UTC, Vrickk commented on src/modules/chattingHandler.ts
> +    return result;
쿼리문이라 Thunder Array 형식으로 반환될건데 제가 테스트후에 다시 알려드리겠습니다.

2023-03-21 13:18 UTC, KWY0218 commented on src/services/ChatService.ts
> +  userId: ObjectId,
string

2023-03-21 13:18 UTC, KWY0218 commented on src/services/ChatService.ts
> +      let result = await PersonalChatRoom.findById(i); //PersonalChatRoom에서 members 안에 든 id를 검색.
`let i of member` 
보다 `let member of members ` 가 가독성 좋은 변수명인 것 같습니다.
그러기 위해선 위 const member 말고 const members로 정의하면 좋을 것 같습니다

2023-03-21 13:18 UTC, KWY0218 commented on src/services/ChatService.ts
> +        result.isAlarm = !isAlarm;
파라미터로 넣은 값을 반전 시키는 것이 아닌 그냥 넣어 주면 될 것 같습니다..!

2023-03-21 13:36 UTC, KWY0218 reviewed
👍

2023-03-22 14:56 UTC, Vrickk commented on src/modules/chattingHandler.ts
> +    return result;
반환 형식 ThunderInfo[] | null로 명시했습니다.

2023-03-22 16:44 UTC, KWY0218 reviewed
구웃~ 👍

2023-03-22 16:44 UTC, KWY0218 commented on src/modules/chattingHandler.ts
> +    }
빈리스트 반환이 좋을 것 같습니다..!

2023-03-22 16:44 UTC, KWY0218 commented on src/modules/chattingHandler.ts
> +
채팅 알람은 2번으로 알고 있습니다..!

2023-03-22 16:44 UTC, KWY0218 commented on src/services/chat/ChatService.ts
> +
여기 아래서 부터 `const` 를 사용해도 지장이없어 보이는데 `let` 을 사용해야 하는 이유가 있을까요?

2023-03-22 16:44 UTC, KWY0218 commented on src/services/chat/ChatService.ts
> +      }
chat.toString() 이 아닌 chat.sender._id 이 맞는 것 같습니다

2023-03-22 17:03 UTC, Vrickk commented on src/services/chat/ChatService.ts
> +
테스트할때 반복문 에러 방지를 위해 let으로 일단 설정해놨었습니다. 수정했습니다.

2023-03-23 06:33 UTC, Vrickk commented on src/services/chat/ChatService.ts
> +      }
userDto 수정 시 같이 state 여부 수정하도록 했습니다.

2023-03-23 07:21 UTC, Vrickk commented on src/services/chat/ChatService.ts
> +      }
수정했습니다

2023-03-23 07:21 UTC, Vrickk commented on src/modules/chattingHandler.ts
> +
수정했습니다.

2023-03-23 07:32 UTC, KWY0218 approved these changes
구웃~ 👍

2023-03-23 08:21 UTC, merged