HAN-80 [feat] create  get api UserThunderRecord
Koreatech-Thunder/Thunder-Server pull request #23
Opened 2023-03-20 13:47 UTC by hansongyi2020

## 관련 이슈 번호 🔎

- HAN-80 

<br>

## 주요 변경 사항 🔑

- create  get api UserThunderRecord

<br>

## 하고싶은 말 📢

-

<br>

## 관련 스크린샷 (선택) 📷

-

<br>

## 참고자료 📚

-

<br>

2023-03-20 14:10 UTC, KWY0218 requested changes

2023-03-20 14:10 UTC, KWY0218 commented on src/services/user/UserService.ts
> +
오늘보다 deadline이 지난 thunder 들 로만 주면 될 것 같습니다..!

2023-03-21 07:34 UTC, KWY0218 requested changes
코멘트 확인해주세요~!

2023-03-21 07:34 UTC, KWY0218 commented on src/controllers/thunder/ThunderController.ts
> +    const userId = req.params.userId;
미들웨어에서 userId를 body 안에 넣을텐데
수정한 이유가 있을까요?

2023-03-21 07:34 UTC, KWY0218 commented on src/routes/ThunderRouter.ts
> +router.get('/:userId', ThunderController.findThunderAll);
userId는 Path 가 아닌 header 에서 access token을 디코딩 한 후 추출해서 가져옵니다.
다시 수정해주세요

2023-03-21 07:34 UTC, KWY0218 commented on src/services/thunder/ThunderService.ts
> +            thunderid: thunder._id,
`thunderId`
camel case 유의해주세요

2023-03-21 07:38 UTC, hansongyi2020 commented on src/controllers/thunder/ThunderController.ts
> +    const userId = req.params.userId;
아! 아직 제 서버에서 토큰이 없어 구현할 때는 미들웨어 거치지 않고 임시로 userId 넣어서 하고 있습니다

2023-03-21 07:40 UTC, KWY0218 commented on src/controllers/thunder/ThunderController.ts
> +    const userId = req.params.userId;
근데 테스트만 할 때만 하고 pr 올릴 땐 수정해서 올려주세요~

2023-03-21 07:40 UTC, hansongyi2020 commented on src/routes/ThunderRouter.ts
> +router.get('/:userId', ThunderController.findThunderAll);
이 부분도 동일하게 userId를 params로 test한 뒤 오류가 없으면 미들웨어 적용시킬 겁니다..!

2023-03-21 07:40 UTC, HANSONGYI1218 commented on src/services/thunder/ThunderService.ts
> +            thunderid: thunder._id,
수정하겠습니다!

2023-03-21 07:45 UTC, hansongyi2020 commented on src/controllers/thunder/ThunderController.ts
> +    const userId = req.params.userId;
다시 pr 올렸습니다.!

2023-03-21 12:26 UTC, KWY0218 requested changes

2023-03-21 12:26 UTC, KWY0218 commented on src/routes/UserRouter.ts
> +router.get('/record/', auth.auth, UserController.findUserThunderRecord);
```suggestion
router.get('/record', auth.auth, UserController.findUserThunderRecord);
```

2023-03-21 15:19 UTC, Vrickk approved these changes

2023-03-21 15:19 UTC, Vrickk commented on src/services/user/UserService.ts
> +        thunderRecord.push({
thunderRecord는 별도 모델을 사용하는 것으로 알고있는데  여기서는 Thunder를 push 및 pull 하는 것으로 보입니다..!

2023-03-22 05:55 UTC, hansongyi2020 commented on src/services/user/UserService.ts
> +
수정했습니다!

2023-03-22 06:05 UTC, KWY0218 commented on src/services/thunder/ThunderService.ts
> +    }).sort({createdAt: 'desc'});
혹시 -1을 하는 이유가 있을까요??

2023-03-22 06:37 UTC, hansongyi2020 commented on src/services/thunder/ThunderService.ts
> +    }).sort({createdAt: 'desc'});
currenTime.getDate() 현재날짜에서 1을 빼면 하루 전입니다!

2023-03-22 06:44 UTC, hansongyi2020 commented on src/services/thunder/ThunderService.ts
> +    }).sort({createdAt: 'desc'});
![image](https://user-images.githubusercontent.com/74229148/226823149-7c874039-5a44-46a6-8878-b269b855f9b4.png)

2023-03-22 06:45 UTC, hansongyi2020 commented on src/services/thunder/ThunderService.ts
> +    }).sort({createdAt: 'desc'});
어제 만들어서 시간 안 지난 번개 방 필터링 해서 잘 나옵니다!!! response 예시입니다!

2023-03-22 08:11 UTC, KWY0218 approved these changes
👍

2023-03-22 12:52 UTC, KWY0218 requested changes

2023-03-22 12:52 UTC, KWY0218 commented on src/models/User.ts
> +    unique: true,
요거 삭제 바람~~

2023-03-22 13:08 UTC, KWY0218 approved these changes
👍

2023-03-22 14:05 UTC, merged