HAN-125 [feat] create hashtag alarm to user
Koreatech-Thunder/Thunder-Server pull request #26
Opened 2023-03-22 08:45 UTC by hansongyi2020

## 관련 이슈 번호 🔎

- HAN-125

<br>

## 주요 변경 사항 🔑

-  create hashtag alarm to user

<br>

## 하고싶은 말 📢

- ThunderService에 createThunder api 봐 주세요!

<br>

## 관련 스크린샷 (선택) 📷

-

<br>

## 참고자료 📚

-

<br>

2023-03-22 08:49 UTC, KWY0218 requested changes

2023-03-22 08:49 UTC, KWY0218 commented on src/services/thunder/ThunderService.ts
> +    }
user.isAlarms[0] 이 true 일 때만 보내도록 수정하면 될 것 같습니다

2023-03-22 13:38 UTC, Vrickk approved these changes
👍

2023-03-22 13:38 UTC, Vrickk commented on src/interfaces/user/UserAlarmStateResponseDto.ts
> +  isAlarms: Boolean[];
만약 안불러와지면 [Boolean]으로 바꿔주세요~

2023-03-22 13:38 UTC, Vrickk commented on src/interfaces/user/UserInfo.ts
> +  isAlarms: Boolean[];
만약 안불러와지면 [Boolean]으로 바꿔주세요~

2023-03-22 13:38 UTC, Vrickk commented on src/models/User.ts
> +      type: Boolean,
만약 안불러와지면 [Boolean]으로 바꿔주세요~

2023-03-22 14:56 UTC, hansongyi2020 commented on src/services/thunder/ThunderService.ts
> +    }
수정했습니다!

2023-03-22 14:58 UTC, KWY0218 commented on src/services/thunder/ThunderService.ts
> +      }
user._id 를 보내줘야 합니다..!

2023-03-22 15:00 UTC, HANSONGYI1218 commented on src/services/thunder/ThunderService.ts
> +      }
네! 수정했습니다

2023-03-22 15:03 UTC, KWY0218 approved these changes
👍

2023-03-22 15:06 UTC, Vrickk approved these changes

2023-03-22 15:37 UTC, Vrickk approved these changes

2023-03-22 15:37 UTC, Vrickk commented on src/routes/ThunderRouter.ts
> -  '/hashtags',
미들웨어 삭제된 이유가 있을까요??

2023-03-22 15:37 UTC, hansongyi2020 commented on src/routes/ThunderRouter.ts
> -  '/hashtags',
아! 맞다..! 수정하겠습니다!

2023-03-22 15:53 UTC, Vrickk approved these changes

2023-03-22 18:03 UTC, Vrickk approved these changes

2023-03-23 01:06 UTC, KWY0218 approved these changes
구우웃~ 👍 
수정한 내용들 pr에도 정리하면 나중에 확인할 때 좋을 것 같습니다~~!

2023-03-23 10:26 UTC, merged