[feat] HAN-87 카카오 및 fcm 로그인
Koreatech-Thunder/Thunder-Server pull request #3
Opened 2023-02-20 13:24 UTC by Vrickk

Kakao 및 FCM 토큰 발급 및 로그인, 토큰 유효성 검사 기능 구현.

## 관련 이슈 번호 🔎

-[HAN-87](https://koreatech-hanbun.atlassian.net/browse/HAN-87?atlOrigin=eyJpIjoiMDAxNDFlMjNkYWQ2NDNkMDgyMDk5MjBhNThjZmJlZGUiLCJwIjoiaiJ9)

<br>

## 주요 변경 사항 🔑

- 1. Kakao  토큰을 로그인 시 발급할 수 있도록 하였습니다. FCM 토큰은 [Firebase와 어플리케이션 연결 후, 어플리케이션 측에서 확인해야 한다고 하여](https://firebase.google.com/docs/web/setup?hl=ko) 우선 테스트 문구로 남겨놓았습니다. kakao 로그인 시 토큰 내 kakaoId 정보가 유효하지 않다면 Bad Request 오류를 전달하고, 해당 kakaoId를 가진 유저가 아직 없다면 No User Found 메시지를 전달합니다. (회원가입으로 이동하는 것을 전제로 하였습니다.) 해당 kakaoId를 가진 유저가 있다면 jwt.sign으로 kakao 및 fcm 토큰을 암호화하여 발급합니다.
- 2. 카카오와 fcm 토큰의 유효성을 검사하는 verifyToken 기능을 구현하였습니다.
- 3. 각 유저의 kakaoId 정보를 확인하기 위해 User 스키마에 kakaoId 필드를 추가했습니다. 

<br>

## 하고싶은 말 📢

- 토큰에 대한 이해 부족으로 아직 미완성에 가까운 부분이 많습니다. 빠른 시일 내에 완벽하게 구현해보도록 하겠습니다.
- 에러 발생 시 클라이언트 측으로 발송할 코드 혹은 정보에 관한 명확한 협의가 필요할 것 같습니다.
- Firebase Key는 보안 문제를 우려하여 같이 커밋하지 않았습니다. 필요하실 경우 말해주세요.

<br>

## 관련 스크린샷 (선택) 📷

![image](https://user-images.githubusercontent.com/36978332/220120418-eb6a6a0b-8b43-4ecd-aafb-a52cbf5d774c.png)

해당 kakaoId를 가진 유저가 있을 경우 kakao 및 fcm 토큰을 jwt로 발급한다.

<br>

## 참고자료 📚

-

<br>

2023-02-20 15:15 UTC, KWY0218 requested changes
리뷰 하다가 생각 드는건데 번개 쪽 송이 담당 아닌가요...?

2023-02-20 15:15 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +    const accessToken = await AuthService.login(kakaoToken);
fcm토큰도 같이 보낼거라서 이 부분도 반영하면 좋을 것 같습니다.

2023-02-20 15:15 UTC, KWY0218 commented on src/services/ThunderService.ts
> +        });
`host` 속성은 저번 카톡 때 얘기한 거 참고해주세요..!

2023-02-20 15:15 UTC, KWY0218 commented on src/services/ThunderService.ts
> +}
1. 유저에 따른 번개 방 상태 로직이 빠진것 같습니다.

2023-02-22 08:30 UTC, KWY0218 reviewed
답변 확인해주세요!

2023-02-22 08:30 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +}
1. 저는 kakao token하고 fcm token 값을 body에 넣어서 보내고 있습니다. 이 점 참고해서 토큰 값이 유효한지 확인하면 좋을 것 같습니다.
2. 200, 로그인 성공 (새로운 회원일 때)
3. 401, 유효하지 않은 토큰
4. 404, 탈퇴했거나 존재하지 않는 유저입니다.
5. 500, 서버 오류

하우스에서는 이런 식으로 오류 코드 사용 중입니다.
이점 참고해서 에러처리도 하면 좋을 것 같습니다.

2023-02-22 08:30 UTC, KWY0218 commented on src/routes/index.ts
> +router.use('/thunder', ThunderRouter);
thunder 관련 로직인 것 같아서 삭제해야할 것 같습니다.

2023-02-22 08:30 UTC, KWY0218 commented on src/services/UserService.ts
> +}
해당 코드들은 이전 lab 레파지토리에서 만든 코드를 가져온 것일까요?
맞다면 다른 브랜치에서 작업해야 할 것 같다는 생각이 듭니다..!

2023-02-22 08:30 UTC, KWY0218 commented on src/services/AuthService.ts
> +}
로그 아웃을 하고 해당 유저의 `isLogout` 속성을 true로 바꿔주는 로직이 없는 것 같습니다.

2023-02-22 08:30 UTC, KWY0218 commented on src/services/AuthService.ts
> +        }
![image](https://user-images.githubusercontent.com/82709044/220564730-40ab3d43-3858-4326-981d-5b2e7bc5b2cc.png)
419 error code 는 만료되었다는 느낌이 아닌 것 같습니다..! 다른 에러코드가 어울리지 않을까 생각이 드는데 어떻게 생각하시나요?

2023-02-24 13:08 UTC, Vrickk commented on src/services/UserService.ts
> +}
로그인 테스트용 코드를 같이 푸쉬한 것 같네요. 추후 User 및 Thunder 관련 필요없는 코드는 다음 커밋에서 삭제하도록 하겠습니다.

2023-02-24 13:11 UTC, Vrickk commented on src/services/AuthService.ts
> +        }
카카오 로그인에서 Access 토큰은 사용자 인증에 사용됩니다. 이 Access 토큰이 만료되었다는 것은 곧 인증이 만료되었다는 것을 의미합니다. 해당 코드는 토큰이 만료되었을 때, 즉 사용자 인증이 만료되어 다시 인증해야 할 때 사용되므로 Authentication Timeout을 의미하는 419 코드를 사용하게 되었습니다.

[이 블로그](https://kakao-tam.tistory.com/86)의 내용을 참고했습니다.

2023-02-24 13:12 UTC, Vrickk commented on src/services/AuthService.ts
> +}
깜빡했네요...

2023-02-24 14:59 UTC, KWY0218 commented on src/services/AuthService.ts
> +        }
![image](https://user-images.githubusercontent.com/82709044/221210835-1ffe6314-bfd7-4126-8fc3-2bbbf1b5c061.png)
해당 블로그에서도 토큰 만료 시 `419`가 아닌  `401` 에러코드를 반환하는 것 같습니다..!

2023-02-28 16:53 UTC, Vrickk commented on src/services/AuthService.ts
> +        }
그렇다면 401로 코드 변경하도록 하겠습니다.

2023-03-01 10:46 UTC, Vrickk commented on src/services/AuthService.ts
> +}
추가했습니다.

2023-03-01 10:46 UTC, Vrickk commented on src/services/AuthService.ts
> +        }
변경 완료 했습니다.

2023-03-01 13:29 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +    const kakaoToken = req.headers["kakaoToken"];
header -> body

2023-03-01 13:29 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +
```suggestion

    const accessToken = await AuthService.refresh(userId, kakaoRefreshToken, fcmRefreshToken);

```

2023-03-01 13:29 UTC, KWY0218 commented on src/services/AuthService.ts
> +const login = async (kakaoToken: any, fcmToken: any) => {
파라미터 `userId` 추가

2023-03-03 14:24 UTC, Vrickk commented
@KWY0218 @hansongyi2020  
https://inpa.tistory.com/entry/NODE-%F0%9F%93%9A-%EC%B9%B4%EC%B9%B4%EC%98%A4-%EB%A1%9C%EA%B7%B8%EC%9D%B8-Passport-%EA%B5%AC%ED%98%84

현재 해보고 있는 passport-kakao를 이용한 카카오 로그인 방식입니다. 기존에 저희가 이야기한 방식은 클라이언트 측에서 카카오, fcm 토큰을 보내면 서버 측에서 유효한지 검사하고 유효할 시 토큰을 jwt로 변환한 후 발급하는 방식이었는데요. 여기서는 라우터를 통해서 카카오 로그인 페이지에서 로그인 시, 식별값을 서버로 전달합니다. 식별값에는 accessToken과 refreshToken이 포함되어 있습니다. 서버의 kakaoStrategy.ts에서 가입이력을 조사하여 가입이력이 있으면 성공 done()을 보내고, 가입이력이 없다면 경우에 따라 바로 회원가입을 시킬 수 있다고 합니다. 클라이언트에는 세션쿠키가 보내짐으로써 로그인 인증이 완료됩니다.

passport로 진행 시 기존에 진행했던 구조와 많이 달라질 수 있어 이렇게 글을 남겨봅니다. 확인해 주시고, 의견이 있으시다면 써 주시길 바랍니다.

2023-03-04 12:20 UTC, hansongyi2020 approved these changes

2023-03-04 14:12 UTC, KWY0218 commented
@Vrickk 
레퍼런스 참고해서 하면 될 거 같아요~!

2023-03-04 14:26 UTC, Vrickk commented on src/services/AuthService.ts
> +const login = async (kakaoToken: any, fcmToken: any) => {
파라미터 추가 대신 decode한 jwt 토큰에서 userid 정보를 읽어오는 것으로 처리했습니다. 로그인에는 userId 파라미터가 필요하지 않을 것 같습니다.

2023-03-05 06:45 UTC, KWY0218 reviewed
작업하시느라 수고하셨습니다. 커멘트 참고해주세요!

2023-03-05 06:45 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +    const refreshToken = req.body["refreshToken"];
어떤 유저의 refresh 토큰인지 구분하기 위해 미들웨어에서 accesstoken을 디코딩해서 얻은 userId 를 body에서 꺼내서 service에 넘겨줘야 할 거 같습니다.

추가)
service 에서 userId를 디코딩하는 것 같은데, 저희는 controller에서 뽑고 service 로 넘겨주는 방식을 많이 사용하는 것 같은데 service에서 userId를 뽑는 이유가 있을까요?

2023-03-05 06:45 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +
```suggestion

        const data = await AuthService.refresh(userId, accessToken, refreshToken);

```

2023-03-05 06:45 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +        }
에러 코드 관련해서 단순 문자열 보다 enum 클래스나 상수를 사용해서 타입을 제한 하는 것은 어떠나요?

2023-03-05 06:45 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +    const accessToken = req.body["accessToken"]
로그아웃을 하는데 fcm token과 access token이 필요한 이유를 모르겠습니다.
미들웨어에서 access token을 디코딩 한 후에 userId만 service에 넘겨도 상관 없다고 생각하는데 어떻게 생각하시나요?

2023-03-05 06:45 UTC, KWY0218 commented on src/services/UserService.ts
> +}
userList를 가져와서 어디에 사용하시나요? 👀

2023-03-05 06:45 UTC, KWY0218 commented on src/services/AuthService.ts
> +            return accessToken;
UserService 에 `createUser` 메서드가 있는데 이렇게 저장하는 이유와 만약 이런식으로 저장한다면 UserService 내에 있는 `createUser` 메서드는 사용하지 않는 메서드 같아 보이는데 어떻게 생각하시나요?

2023-03-05 06:45 UTC, KWY0218 commented on src/services/UserService.ts
> +import { UserResponseDto } from '../interfaces/user/UserResponseDto';
해당 UserService , UserController 는 해당 피알에서 따로 사용하지 않는 것 같습니다. 어디서 사용하는지 궁금합니다!

2023-03-05 10:53 UTC, Vrickk commented on src/services/UserService.ts
> +}
이슈 내용과 상관없는 테스트 기능입니다. 수정했습니다.

2023-03-05 11:05 UTC, Vrickk commented on src/controllers/AuthController.ts
> +        }
현재 message.ts처럼 이러한 토큰 관련 에러들만 취급하는 파일을 하나 만들까 생각중입니다.

2023-03-05 11:08 UTC, Vrickk commented on src/services/UserService.ts
> +import { UserResponseDto } from '../interfaces/user/UserResponseDto';
refresh와 logout에서 유저 정보를 Update할 때, 그리고 userId를 이용하여 유저 정보를 찾아낼 때 UserService에서의 메서드를 이용합니다. Controller는 카카오 기능 관련으로만 사용되는 findUserByKakao 기능 때문에 같이 커밋하였습니다.

2023-03-05 11:19 UTC, Vrickk commented on src/services/AuthService.ts
> +            return accessToken;
createUser 메서드를 이용 시 User가 아닌 Promise 형식으로 인식하여 액세스 토큰을 얻기 위해 _id를 불러오거나 하는 과정에 애로사항이 있어 User 객체를 직접 생성하는 방향으로 작성하게 되었습니다.

2023-03-05 11:22 UTC, Vrickk commented on src/controllers/AuthController.ts
> +    const accessToken = req.body["accessToken"]
fcmToken은 유저가 여러 기기에서 로그인한 상황을 상정했습니다. fcm 토큰은 기기별로 고유한 성질을 지닙니다. 따라서 현재 기기에서 로그아웃할 시 현재 기기의 fcm 토큰만 삭제하는 작업을 작성했고 이를 위해 현재 기기의 fcm 토큰을 필요로 합니다.
accessToken은 카카오 서버에 로그아웃 요청을 보내는 데 필요합니다.

2023-03-05 11:25 UTC, Vrickk commented on src/controllers/AuthController.ts
> +    const refreshToken = req.body["refreshToken"];
액세스 토큰에 유저 id 정보가 포함되어 있어 service에서 userId를 뽑는 방향으로 작성했습니다. userId를 body에서 같이 넘겨주는 방식이 더 편하다면 수정하도록 하겠습니다.

2023-03-06 01:58 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +    const refreshToken = req.body["refreshToken"];
아닙니다~! 이대로 합시다~!

2023-03-06 01:59 UTC, Vrickk commented on src/controllers/AuthController.ts
> +    const refreshToken = req.body["refreshToken"];
알겠습니다!

2023-03-06 02:00 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +    const accessToken = req.body["accessToken"]
클라이언트에서 fcm 토큰을 받아오는 것이 아닌 그러면 userId를 통해서 해당 유저의 정보를 가져오고 db에 저장되어 있는  fcm 토큰을 사용하면 될 것 같습니다.

2023-03-06 02:02 UTC, KWY0218 commented on src/services/UserService.ts
> +import { UserResponseDto } from '../interfaces/user/UserResponseDto';
아 메서드를 사용안하는줄 알았습니다..! 확인했습니다~!

2023-03-06 02:11 UTC, Vrickk commented on src/controllers/AuthController.ts
> +    const accessToken = req.body["accessToken"]
userId만 받아서 그걸로 참조하는 방식 말씀하시는거죠??

2023-03-06 02:14 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +    const accessToken = req.body["accessToken"]
넹넹~!

2023-03-06 06:33 UTC, Vrickk commented on src/controllers/AuthController.ts
> +    const accessToken = req.body["accessToken"]
@KWY0218  accessToken은 유저 정보에서 참조할 수 있을것 같습니다만 fcmToken은 아무래도 현재 기기의 토큰이 무엇인지 구별할 방법이 마땅히 없어서 기기에서 토큰 정보를 읽어와야 할 것 같습니다!

2023-03-06 06:37 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +    const accessToken = req.body["accessToken"]
User entity를 보면 fcmToken 속성 안에 fcm token 정보를 저장하고 있습니다.
로그아웃을 한다는 의미는 이미 해당 유저 내엔 fcmToken이 있다는 소리고
access token을 통해서 userId를 뽑은 다음에
db에서 해당 userId의 유저 정보를 불러온 다음에 그 정보에서 fcm token을 추출하면 될 것 같습니다

2023-03-06 06:43 UTC, Vrickk commented on src/controllers/AuthController.ts
> +    const accessToken = req.body["accessToken"]
위에서 말씀드렸듯이 fcmToken은 다른 기기에서의 로그인 역시 상정하고 만든 필드라 [String] 형식입니다. 따라서 array 안에 여러 fcmToken이 존재하는데, 현재 기기의 fcmToken을 알 수 있는 방식이 현재로써는 클라에서 받아오는거밖엔 떠오르지않네요...

물론 현재 기기에서 로그인하면 다른 기기에서는 가차없이 로그아웃하는 방법도 있습니다.

2023-03-07 06:07 UTC, Vrickk commented on src/controllers/AuthController.ts
> +        }
@KWY0218 tokenStatus 모듈을 새로 추가했습니다.

2023-03-07 06:56 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +    const accessToken = req.body["accessToken"]
아아 fcm 토큰은 이해했습니다..!

2023-03-07 06:59 UTC, KWY0218 commented on src/services/AuthService.ts
> +    });
그런데 이 과정이 필요한 이유가 궁금합니다.
login 에서 get api를 통해서 user 의 정보를 가져오기만 하지 user/login 라우터를 통해 로그인 하는 과정은 안보이므로
해당 user/logout 라우터의 post 요청은 없어도 되는 로직이 아닌가 생각이 듭니다..!

2023-03-07 07:17 UTC, Vrickk commented on src/services/AuthService.ts
> +    });
삭제 내용 커밋했습니다. 로그인이 있으면 로그아웃 역시 있어야하는게 아닌가? 하고 넣은 로직인데 좀 더 찾아보니 logout보다는 unlink를 더 많이 쓰더군요...

2023-03-07 07:17 UTC, Vrickk commented on src/controllers/AuthController.ts
> +    const accessToken = req.body["accessToken"]
accessToken은 userId를 통해 얻도록 수정했습니다!

2023-03-07 12:00 UTC, KWY0218 commented on src/models/User.ts
> +  },
User entity 내에 access token 과 refresh token 을 저장 안해도 됩니다.

access token을 재발급할 때 access token 과 refresh token이 필요한데 이 토큰들은 refresh API를 요청할 때 클라이언트에서 줄 것이고, 이렇게 된다면 User Entity 속성으로 access token과 refresh token을 가지고 있어야 할 이유가 없어진다고 생각합니다.

또, refresh 로직을 클라이언트에서 body 값으로 { accessToken: string, refreshToken: string } 형식으로 줄 것이라서 이것을 반영해서 수정하면 좋을 것 같습니다.

2023-03-07 12:00 UTC, KWY0218 commented on src/services/AuthService.ts
> +    }
이제 대신 login 결과 로직에는 단일 값으로 accesstoken을 string으로 반환 중인데 { accessToken: string, refreshToken: string } 객체로 주면 될 것 같습니다.

2023-03-07 12:00 UTC, KWY0218 commented on src/services/AuthService.ts
> +      await user.save();
현재 여기서 `user._id` 는  `save()` 연산을 하지 않았는데 id 할당이 된 상태인가요?

2023-03-07 12:18 UTC, Vrickk commented on src/services/AuthService.ts
> +    }
dto를 하나 파서 묶어서 드려도 되나요?

2023-03-07 12:21 UTC, KWY0218 commented on src/services/AuthService.ts
> +    }
넵넵 좋습니다~!!

2023-03-07 12:33 UTC, Vrickk commented on src/services/AuthService.ts
> +      await user.save();
주객이 전도됐네요... 수정했습니다.

2023-03-07 12:33 UTC, Vrickk commented on src/models/User.ts
> +  },
수정했습니다.

2023-03-07 12:34 UTC, Vrickk commented on src/services/AuthService.ts
> +    }
수정했습니다. AuthResponseDto로 return 하도록 했습니다.

2023-03-07 15:13 UTC, KWY0218 commented on src/services/AuthService.ts
> +      await user.save();
뭔가 save를 한 이후에 해당 getByUserId(userId) 같은 걸로 유저의 정보를 한번 가져와야 _id를 받아서 jwt 변환을 할 수 있을 것 같단 생각이 듭니다..!
왜냐하면 save를 통해서 mongo db 안에 user 인스턴스는 생성이 됐지만 , 42줄에 생성된 변수 `user`엔 변동이 없기 때문에 한번 테스트를 해주시면 감사티비...

2023-03-07 15:56 UTC, Vrickk commented on src/services/AuthService.ts
> +      await user.save();
![11](https://user-images.githubusercontent.com/36978332/223476071-0bec26e2-5199-4a5d-be02-d921a8943414.PNG)
![12](https://user-images.githubusercontent.com/36978332/223476084-5ed2e7d4-0ac7-4fbd-9ece-8dda7f48249f.PNG)

마지막으로 커밋한 판본의 Thunder 테스트 결과입니다.

2023-03-08 00:01 UTC, KWY0218 commented on src/services/AuthService.ts
> +      const refreshToken = jwtHandler.getRefreshToken();
첫번째 사진으론 jwt에 userId가 잘 들어간지 확인할 수 없습니다.
제가 원하는건 51번째 라인에서 access token을 발급할 때 user.id 가 잘 들어가는지가 궁금한것입니다.
그래서 50번 째 라인에서 로그로 user.id 를 출력해서 access token을 발급하기 전에 user.id 가 잘 들어가는지 다시 확인 바랍니당

2023-03-08 00:19 UTC, Vrickk commented on src/services/AuthService.ts
> +      const refreshToken = jwtHandler.getRefreshToken();
![image](https://user-images.githubusercontent.com/36978332/223586125-8fb10b95-4025-4da3-ab32-5effa48d197f.png)

위 이미지의 터미널 로그를 보시면 mongoose id가 정상적으로 출력되는 것을 확인할 수 있겠습니다!

2023-03-08 00:20 UTC, KWY0218 commented on src/services/AuthService.ts
> +      const refreshToken = jwtHandler.getRefreshToken();
다행티비~~ 👍

2023-03-08 00:43 UTC, Vrickk commented on src/services/AuthService.ts
> +            return accessToken;
createUser 삭제하여 커밋했습니다.

2023-03-08 14:32 UTC, KWY0218 commented on src/controllers/AuthController.ts
> +    }
토큰 만료 검사 로직 같은데 미들웨어가 만들어지면 코드 중복일 것 같아서 제거해도 될 거 같습니다.
근데 문득 든 생각
토큰이 만료되서 리프레쉬 토큰을 요청하는데 검사를 해야 하나? 란 의문이 드네요 ... ㅋㅋㅋ

2023-03-08 14:32 UTC, KWY0218 commented on src/services/AuthService.ts
> +    }); //로그아웃 여부 true로 변경하고 fcm 토큰은 다음에 다시 로그인할때 새로 받기 전까지 삭제.
이쪽 아래와 같은 상황일 때 오류가 있을거 같아요
1. 유저가 로그인 함
2. 그 다음 로그아웃함
3. 그러면 fcm 토큰이 없어짐
4. 유저가 다시 로그인 함
5. login api 안에서 해당 유저는 있는 유저라서 fcm 저장하기 전에 로직을 탈출함
6. 로그인을 해도 fcm 토큰이 갱신이 안됌

재로그인 시 이런 문제가 생길 것 같은 생각이 듭니다.

2023-03-08 14:35 UTC, Vrickk commented on src/services/AuthService.ts
> +    }); //로그아웃 여부 true로 변경하고 fcm 토큰은 다음에 다시 로그인할때 새로 받기 전까지 삭제.
이미 존재하는 유저의 fcm토큰은 어떻게 갱신되는지 물어봐도 될까요?

2023-03-08 14:38 UTC, KWY0218 commented on src/services/AuthService.ts
> +    }); //로그아웃 여부 true로 변경하고 fcm 토큰은 다음에 다시 로그인할때 새로 받기 전까지 삭제.
뷰에서 카카오 로그인을 보내면 무조건 kakao token, fcm token을 보낼 겁니다.
이제 갱신 관련 로직은 서버에서 생각해서 해야될 거 같습니다.

2023-03-08 14:38 UTC, Vrickk commented on src/controllers/AuthController.ts
> +    }
그럼 미들웨어때 사용하도록 일단 킵하도록 하겠습니다. 
리프레쉬 토큰은 코드를 갱신할 때 필요한 키 같은 개념이라고 알고 있습니다. 얘가 만료되면 갱신을 아예 못하기 때문에 검사가 필요하긴 할 것 같습니다.

2023-03-08 14:40 UTC, Vrickk commented on src/controllers/AuthController.ts
> +    }
토큰의 수명이 짧을수록 오히려 보안에 도움이 된다는 얘기도 있긴 했습니다. 일단 리프레쉬 토큰같은 경우 액세스 토큰을 갱신하는 데 필요한 열쇠같은 역할을 하기 때문에 검사를 하긴 해야할 것 같습니다.

2023-03-08 14:56 UTC, Vrickk commented on src/services/AuthService.ts
> +    }); //로그아웃 여부 true로 변경하고 fcm 토큰은 다음에 다시 로그인할때 새로 받기 전까지 삭제.
> 이미 있는 유저일 시 에러 발송 전에 fcm토큰만 갱신하고 발송하는 방향으로 하는게 나을까요?

테스트 해보니 에러 발송 전에 fcm 토큰이 잘 변경되는 것을 확인했습니다. 추가적으로 isLogOut 역시 바뀌도록 하였습니다.

2023-03-08 16:59 UTC, KWY0218 commented on src/services/AuthService.ts
> +    }); //로그아웃 여부 true로 변경하고 fcm 토큰은 다음에 다시 로그인할때 새로 받기 전까지 삭제.
읭??? login 로직이 유저가 존재한다면 throw를 날리고, 유저가 존재하지 않을 때에만 fcm 토큰을 저장하는데 
로그인 -> 로그아웃 -> 로그인 할 때 왜 잘되지..?
로직으로만 봤을 때 안될거같은데.. 뭐지 진짜...

2023-03-08 17:00 UTC, KWY0218 commented on src/services/AuthService.ts
> +    }); //로그아웃 여부 true로 변경하고 fcm 토큰은 다음에 다시 로그인할때 새로 받기 전까지 삭제.
[0d73f03](https://github.com/Koreatech-Thunder/Thunder-Server/pull/3/commits/0d73f031c9365b7a28ee35a353df885c66569d8e) 아 커밋 이제 봤네 확인이요~~!

2023-03-08 17:03 UTC, KWY0218 approved these changes
후... 이제 배포하고 클라랑 테스트하면서 수정하는 것 말고는
지금 코드상엔 별다른 문제가 없다고 느껴지네요
그동안 작업하시느라 고생하셨습니다!!!

아 그리고 지금 송이 작업을 보니까 패키지 수정이 있던데 합의 후에 둘 중에 하나 결정해서 패키지를 수정후 머지를 해야할 것 같습니다..!

2023-03-09 11:02 UTC, merged