HAN-96 [feat] create post-thunder api , fix user collection
Koreatech-Thunder/Thunder-Server pull request #4
Opened 2023-02-21 10:34 UTC by hansongyi2020

## 관련 이슈 번호 🔎

- HAN-96

<br>

## 주요 변경 사항 🔑

- create post-thunder api 
- fix user collection_isLogout 추가

<br>

## 하고싶은 말 📢

- isLogout default 값 false로 했는데 확인해 주세요!

<br>

## 관련 스크린샷 (선택) 📷

-

<br>

## 참고자료 📚

-

<br>

2023-02-21 16:20 UTC, KWY0218 reviewed
피알에 적은
- create post-thunder api
- fix user collection_isLogout 추가
이 2 부분만 확인했는데, 리뷰 남긴 부분을 제외하곤 괜찮은 것 같습니다.

또, 이슈 HAN-91 이슈에서 USER COLLECTION 을 수정해달란 요청을 했는데,
다른 브랜치에서 수정하는 것이 아닌 해당 브랜치에서 수정하고 다시 푸시하는 것입니다.
다음번엔 주의 바랍니다!

2023-02-21 16:20 UTC, KWY0218 commented on src/services/ThunderService.ts
> +    });
번개 만들 때 `createdAt` , `updatedAt` 속성 값 넣어줘야 하지 않나요??
@Vrickk 맞을까요~?

2023-02-23 10:12 UTC, hansongyi2020 commented on src/services/ThunderService.ts
> +    });
알겠습니다!

2023-02-24 14:27 UTC, Vrickk requested changes
수고하셨습니다. Thunder에서 테스트해 보고 문제 발견 시 알려드리겠습니다.

2023-02-24 14:27 UTC, Vrickk commented on src/models/User.ts
> +    default: false,
isLogout도 결국엔 유저가 카카오 로그인을 수행하고 유저 정보를 생성할 때 같이 기본값이 정해지는 거라서 isLogout은 default가 false가 맞는거 같습니다.

2023-02-24 14:27 UTC, Vrickk commented on src/interfaces/thunder/ThunderInfo.ts
> +  ceatedAt: Date;
오타가 있네요 createdAt입니다!

2023-02-24 14:27 UTC, Vrickk commented on src/services/ThunderService.ts
> +    });
> 번개 만들 때 `createdAt` , `updatedAt` 속성 값 넣어줘야 하지 않나요?? @Vrickk 맞을까요~?


네. createdAt은 생성될때만 넣어주시고, updatedAt은 해당 글이 수정(Update) 될 때마다 갱신되는 식으로 해 주시면 될 것 같습니다.

2023-02-28 16:51 UTC, Vrickk approved these changes
수고하셨습니다.

2023-03-01 13:59 UTC, closed without merging