HAN-89 [feat] create get-allthunder api, fix HAN-91 findUserHashtag
Koreatech-Thunder/Thunder-Server pull request #5
Opened 2023-02-21 14:10 UTC by hansongyi2020

## 관련 이슈 번호 🔎

- HAN-89

<br>

## 주요 변경 사항 🔑

- create get-allthunder api
- HAN-91 services/UserService/findUserHashtag 에서 Promise<> 반환값 수정

<br>

## 하고싶은 말 📢

-해시태그 지정 없이 전체 번개를 불러올 때 thunderState 필요한지 궁금합니다.
 일단 전체 번개 불러올 때는 필요 없다고 생각돼서 
 interfaces/thunder/response 에서 ThunderAllresponseDto와 ThunderDeatilresponseDto 분리 했습니다.

ThunderAllresponseDto -> thunderState 없음
ThunderDeatilresponseDto  -> thunderState 있음

<br>

## 관련 스크린샷 (선택) 📷

-

<br>

## 참고자료 📚

-

<br>

2023-02-21 16:31 UTC, KWY0218 requested changes
작업하시느라 고생했습니다!
리뷰 확인 바랍니다~!

2023-02-21 16:31 UTC, KWY0218 commented on src/services/ThunderService.ts
> +    });
Thunder 속성에 thunderState 가 들어가면 안됩니다.
db에 추가된 번개는 해당 번개를 만든 사람 뿐만 아니라 다른 유저들도 볼 수 있습니다.
그래서 하나의 번개가 어떤 유저한테는 HOST 이고, 어떤 유저에겐 NON_MEMBER, 어떤 유저에겐 MEMBER 상태라서 thunderState는 번개를 불러올 때 api를 요청하는 userId를 비교하며 줘야 합니다.

2023-02-21 16:31 UTC, KWY0218 commented on src/services/ThunderService.ts
> +    const Allthunder: ThunderAllResponseDto[] = [];
보통 변수명 컨벤션은 lowerCamel 케이스로 소문자 먼저 시작하는 것으로 알고 있습니다.

2023-02-21 16:31 UTC, KWY0218 commented on src/services/UserService.ts
> +    } else {
`User` 스키마를 보면 user를 만들 때 default로 빈 리스트를 넣는 것으로 보입니다. 
그래서 저는 해당 로직이 필요한지 의문이 듭니다...!

2023-02-23 10:10 UTC, hansongyi2020 commented on src/services/UserService.ts
> +    } else {
아! 그렇네요..!! 알겠습니다

2023-02-24 14:19 UTC, Vrickk requested changes
API 구현 수고하셨습니다.

2023-02-24 14:19 UTC, Vrickk commented on src/interfaces/thunder/ThunderInfo.ts
> +  updateAt: Date;
createdAt 오타가 있는 것 같습니다!

2023-02-24 14:19 UTC, Vrickk commented on src/interfaces/thunder/request/ThunderCreateDto.ts
> +  deadline: string;
thunderInfo에서는 Date형으로 받는데 여기서는 string이네요. 혹시 테스트용인가요?

2023-02-24 14:19 UTC, Vrickk commented on src/modules/statusCode.ts
> +  CONFLICT: 409,
errorGenerator 및 message에서는 DUPLICATED라고 되어있는 부분이네요. 둘이 따로 쓰임새가 있는건가요?

2023-02-24 14:19 UTC, Vrickk commented on src/models/Thunder.ts
> +  ceatedAt: {
thunderInfo와 마찬가지로 createdAt 오타가 있는 것 같습니다!

2023-03-01 14:00 UTC, closed without merging