HAN-90 [feat] create get-hashtagThunder api
Koreatech-Thunder/Thunder-Server pull request #6
Opened 2023-02-21 16:03 UTC by hansongyi2020

## 관련 이슈 번호 🔎

- HAN-90

<br>

## 주요 변경 사항 🔑

- create get-hashtagThunder api

<br>

## 하고싶은 말 📢

-

<br>

## 관련 스크린샷 (선택) 📷

-

<br>

## 참고자료 📚

-

<br>

2023-02-21 16:34 UTC, KWY0218 requested changes
리뷰 확인 바랍니다~!!

2023-02-21 16:34 UTC, KWY0218 commented on src/services/ThunderService.ts
> +    const Hashtagthunder: ThunderAllResponseDto[] = [];
lowerCamelCase 참고 바랍니다!

2023-02-21 16:34 UTC, KWY0218 commented on src/controllers/ThunderController.ts
> +    res.status(statusCode.OK).send(data);
클라 입장에서 null 말고, 빈 리스트로 주면 좋을 것 같습니다...!

2023-02-23 10:11 UTC, hansongyi2020 commented on src/controllers/ThunderController.ts
> +    res.status(statusCode.OK).send(data);
알겠습니다!

2023-02-24 14:31 UTC, Vrickk requested changes
수고하셨습니다.

2023-02-24 14:31 UTC, Vrickk commented on src/services/ThunderService.ts
> +      thunderState: 'HOST',
createdAt과 updatedAt이 누락된 것 같습니다!

2023-03-01 14:00 UTC, closed without merging